// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ClientMessageDtos.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EventStore.Client.Messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NewEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_id", IsRequired = true)]
        public byte[] EventId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_type", IsRequired = true)]
        public string EventType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"data_content_type", IsRequired = true)]
        public int DataContentType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"metadata_content_type", IsRequired = true)]
        public int MetadataContentType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"data", IsRequired = true)]
        public byte[] Data { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"metadata")]
        public byte[] Metadata
        {
            get { return __pbn__Metadata; }
            set { __pbn__Metadata = value; }
        }
        public bool ShouldSerializeMetadata() => __pbn__Metadata != null;
        public void ResetMetadata() => __pbn__Metadata = null;
        private byte[] __pbn__Metadata;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventRecord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_number", IsRequired = true)]
        public long EventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"event_id", IsRequired = true)]
        public byte[] EventId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"event_type", IsRequired = true)]
        public string EventType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"data_content_type", IsRequired = true)]
        public int DataContentType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"metadata_content_type", IsRequired = true)]
        public int MetadataContentType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"data", IsRequired = true)]
        public byte[] Data { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"metadata")]
        public byte[] Metadata
        {
            get { return __pbn__Metadata; }
            set { __pbn__Metadata = value; }
        }
        public bool ShouldSerializeMetadata() => __pbn__Metadata != null;
        public void ResetMetadata() => __pbn__Metadata = null;
        private byte[] __pbn__Metadata;

        [global::ProtoBuf.ProtoMember(9, Name = @"created")]
        public long Created
        {
            get { return __pbn__Created.GetValueOrDefault(); }
            set { __pbn__Created = value; }
        }
        public bool ShouldSerializeCreated() => __pbn__Created != null;
        public void ResetCreated() => __pbn__Created = null;
        private long? __pbn__Created;

        [global::ProtoBuf.ProtoMember(10, Name = @"created_epoch")]
        public long CreatedEpoch
        {
            get { return __pbn__CreatedEpoch.GetValueOrDefault(); }
            set { __pbn__CreatedEpoch = value; }
        }
        public bool ShouldSerializeCreatedEpoch() => __pbn__CreatedEpoch != null;
        public void ResetCreatedEpoch() => __pbn__CreatedEpoch = null;
        private long? __pbn__CreatedEpoch;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResolvedIndexedEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event", IsRequired = true)]
        public EventRecord Event { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"link")]
        public EventRecord Link { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResolvedEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event", IsRequired = true)]
        public EventRecord Event { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"link")]
        public EventRecord Link { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"commit_position", IsRequired = true)]
        public long CommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"prepare_position", IsRequired = true)]
        public long PreparePosition { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WriteEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expected_version", IsRequired = true)]
        public long ExpectedVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"events")]
        public global::System.Collections.Generic.List<NewEvent> Events { get; } = new global::System.Collections.Generic.List<NewEvent>();

        [global::ProtoBuf.ProtoMember(4, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WriteEventsCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public OperationResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(3, Name = @"first_event_number", IsRequired = true)]
        public long FirstEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"last_event_number", IsRequired = true)]
        public long LastEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"prepare_position")]
        public long PreparePosition
        {
            get { return __pbn__PreparePosition.GetValueOrDefault(); }
            set { __pbn__PreparePosition = value; }
        }
        public bool ShouldSerializePreparePosition() => __pbn__PreparePosition != null;
        public void ResetPreparePosition() => __pbn__PreparePosition = null;
        private long? __pbn__PreparePosition;

        [global::ProtoBuf.ProtoMember(6, Name = @"commit_position")]
        public long CommitPosition
        {
            get { return __pbn__CommitPosition.GetValueOrDefault(); }
            set { __pbn__CommitPosition = value; }
        }
        public bool ShouldSerializeCommitPosition() => __pbn__CommitPosition != null;
        public void ResetCommitPosition() => __pbn__CommitPosition = null;
        private long? __pbn__CommitPosition;

        [global::ProtoBuf.ProtoMember(7, Name = @"current_version")]
        public long CurrentVersion
        {
            get { return __pbn__CurrentVersion.GetValueOrDefault(); }
            set { __pbn__CurrentVersion = value; }
        }
        public bool ShouldSerializeCurrentVersion() => __pbn__CurrentVersion != null;
        public void ResetCurrentVersion() => __pbn__CurrentVersion = null;
        private long? __pbn__CurrentVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteStream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expected_version", IsRequired = true)]
        public long ExpectedVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hard_delete")]
        public bool HardDelete
        {
            get { return __pbn__HardDelete.GetValueOrDefault(); }
            set { __pbn__HardDelete = value; }
        }
        public bool ShouldSerializeHardDelete() => __pbn__HardDelete != null;
        public void ResetHardDelete() => __pbn__HardDelete = null;
        private bool? __pbn__HardDelete;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeleteStreamCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public OperationResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(3, Name = @"prepare_position")]
        public long PreparePosition
        {
            get { return __pbn__PreparePosition.GetValueOrDefault(); }
            set { __pbn__PreparePosition = value; }
        }
        public bool ShouldSerializePreparePosition() => __pbn__PreparePosition != null;
        public void ResetPreparePosition() => __pbn__PreparePosition = null;
        private long? __pbn__PreparePosition;

        [global::ProtoBuf.ProtoMember(4, Name = @"commit_position")]
        public long CommitPosition
        {
            get { return __pbn__CommitPosition.GetValueOrDefault(); }
            set { __pbn__CommitPosition = value; }
        }
        public bool ShouldSerializeCommitPosition() => __pbn__CommitPosition != null;
        public void ResetCommitPosition() => __pbn__CommitPosition = null;
        private long? __pbn__CommitPosition;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionStart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"expected_version", IsRequired = true)]
        public long ExpectedVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionStartCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction_id", IsRequired = true)]
        public long TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public OperationResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionWrite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction_id", IsRequired = true)]
        public long TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"events")]
        public global::System.Collections.Generic.List<NewEvent> Events { get; } = new global::System.Collections.Generic.List<NewEvent>();

        [global::ProtoBuf.ProtoMember(3, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionWriteCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction_id", IsRequired = true)]
        public long TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public OperationResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionCommit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction_id", IsRequired = true)]
        public long TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionCommitCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transaction_id", IsRequired = true)]
        public long TransactionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public OperationResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(4, Name = @"first_event_number", IsRequired = true)]
        public long FirstEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"last_event_number", IsRequired = true)]
        public long LastEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"prepare_position")]
        public long PreparePosition
        {
            get { return __pbn__PreparePosition.GetValueOrDefault(); }
            set { __pbn__PreparePosition = value; }
        }
        public bool ShouldSerializePreparePosition() => __pbn__PreparePosition != null;
        public void ResetPreparePosition() => __pbn__PreparePosition = null;
        private long? __pbn__PreparePosition;

        [global::ProtoBuf.ProtoMember(7, Name = @"commit_position")]
        public long CommitPosition
        {
            get { return __pbn__CommitPosition.GetValueOrDefault(); }
            set { __pbn__CommitPosition = value; }
        }
        public bool ShouldSerializeCommitPosition() => __pbn__CommitPosition != null;
        public void ResetCommitPosition() => __pbn__CommitPosition = null;
        private long? __pbn__CommitPosition;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_number", IsRequired = true)]
        public long EventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadEventCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public ReadEventResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event", IsRequired = true)]
        public ResolvedIndexedEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get { return __pbn__Error ?? ""; }
            set { __pbn__Error = value; }
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

        [global::ProtoBuf.ProtoContract()]
        public enum ReadEventResult
        {
            Success = 0,
            NotFound = 1,
            NoStream = 2,
            StreamDeleted = 3,
            Error = 4,
            AccessDenied = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadStreamEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"from_event_number", IsRequired = true)]
        public long FromEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_count", IsRequired = true)]
        public int MaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadStreamEventsCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"events")]
        public global::System.Collections.Generic.List<ResolvedIndexedEvent> Events { get; } = new global::System.Collections.Generic.List<ResolvedIndexedEvent>();

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public ReadStreamResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"next_event_number", IsRequired = true)]
        public long NextEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"last_event_number", IsRequired = true)]
        public long LastEventNumber { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"is_end_of_stream", IsRequired = true)]
        public bool IsEndOfStream { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"last_commit_position", IsRequired = true)]
        public long LastCommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get { return __pbn__Error ?? ""; }
            set { __pbn__Error = value; }
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

        [global::ProtoBuf.ProtoContract()]
        public enum ReadStreamResult
        {
            Success = 0,
            NoStream = 1,
            StreamDeleted = 2,
            NotModified = 3,
            Error = 4,
            AccessDenied = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commit_position", IsRequired = true)]
        public long CommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prepare_position", IsRequired = true)]
        public long PreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_count", IsRequired = true)]
        public int MaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllEventsCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commit_position", IsRequired = true)]
        public long CommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prepare_position", IsRequired = true)]
        public long PreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"events")]
        public global::System.Collections.Generic.List<ResolvedEvent> Events { get; } = new global::System.Collections.Generic.List<ResolvedEvent>();

        [global::ProtoBuf.ProtoMember(4, Name = @"next_commit_position", IsRequired = true)]
        public long NextCommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"next_prepare_position", IsRequired = true)]
        public long NextPreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"result")]
        [global::System.ComponentModel.DefaultValue(ReadAllResult.Success)]
        public ReadAllResult Result
        {
            get { return __pbn__Result ?? ReadAllResult.Success; }
            set { __pbn__Result = value; }
        }
        public bool ShouldSerializeResult() => __pbn__Result != null;
        public void ResetResult() => __pbn__Result = null;
        private ReadAllResult? __pbn__Result;

        [global::ProtoBuf.ProtoMember(7, Name = @"error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get { return __pbn__Error ?? ""; }
            set { __pbn__Error = value; }
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

        [global::ProtoBuf.ProtoContract()]
        public enum ReadAllResult
        {
            Success = 0,
            NotModified = 1,
            Error = 2,
            AccessDenied = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllEventsFiltered : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commit_position", IsRequired = true)]
        public long CommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prepare_position", IsRequired = true)]
        public long PreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"max_count", IsRequired = true)]
        public int MaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"max_search_window")]
        public int MaxSearchWindow
        {
            get { return __pbn__MaxSearchWindow.GetValueOrDefault(); }
            set { __pbn__MaxSearchWindow = value; }
        }
        public bool ShouldSerializeMaxSearchWindow() => __pbn__MaxSearchWindow != null;
        public void ResetMaxSearchWindow() => __pbn__MaxSearchWindow = null;
        private int? __pbn__MaxSearchWindow;

        [global::ProtoBuf.ProtoMember(5, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"require_master", IsRequired = true)]
        public bool RequireMaster { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"allowed_event_types")]
        public global::System.Collections.Generic.List<string> AllowedEventTypes { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadAllEventsFilteredCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"commit_position", IsRequired = true)]
        public long CommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prepare_position", IsRequired = true)]
        public long PreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"events")]
        public global::System.Collections.Generic.List<ResolvedEvent> Events { get; } = new global::System.Collections.Generic.List<ResolvedEvent>();

        [global::ProtoBuf.ProtoMember(4, Name = @"next_commit_position", IsRequired = true)]
        public long NextCommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"next_prepare_position", IsRequired = true)]
        public long NextPreparePosition { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"is_end_of_stream", IsRequired = true)]
        public bool IsEndOfStream { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"result")]
        [global::System.ComponentModel.DefaultValue(ReadAllFilteredResult.Success)]
        public ReadAllFilteredResult Result
        {
            get { return __pbn__Result ?? ReadAllFilteredResult.Success; }
            set { __pbn__Result = value; }
        }
        public bool ShouldSerializeResult() => __pbn__Result != null;
        public void ResetResult() => __pbn__Result = null;
        private ReadAllFilteredResult? __pbn__Result;

        [global::ProtoBuf.ProtoMember(8, Name = @"error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get { return __pbn__Error ?? ""; }
            set { __pbn__Error = value; }
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

        [global::ProtoBuf.ProtoContract()]
        public enum ReadAllFilteredResult
        {
            Success = 0,
            NotModified = 1,
            Error = 2,
            AccessDenied = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreatePersistentSubscription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_group_name", IsRequired = true)]
        public string SubscriptionGroupName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"start_from", IsRequired = true)]
        public long StartFrom { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"message_timeout_milliseconds", IsRequired = true)]
        public int MessageTimeoutMilliseconds { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"record_statistics", IsRequired = true)]
        public bool RecordStatistics { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"live_buffer_size", IsRequired = true)]
        public int LiveBufferSize { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"read_batch_size", IsRequired = true)]
        public int ReadBatchSize { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"buffer_size", IsRequired = true)]
        public int BufferSize { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"max_retry_count", IsRequired = true)]
        public int MaxRetryCount { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"prefer_round_robin", IsRequired = true)]
        public bool PreferRoundRobin { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"checkpoint_after_time", IsRequired = true)]
        public int CheckpointAfterTime { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"checkpoint_max_count", IsRequired = true)]
        public int CheckpointMaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"checkpoint_min_count", IsRequired = true)]
        public int CheckpointMinCount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"subscriber_max_count", IsRequired = true)]
        public int SubscriberMaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"named_consumer_strategy")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NamedConsumerStrategy
        {
            get { return __pbn__NamedConsumerStrategy ?? ""; }
            set { __pbn__NamedConsumerStrategy = value; }
        }
        public bool ShouldSerializeNamedConsumerStrategy() => __pbn__NamedConsumerStrategy != null;
        public void ResetNamedConsumerStrategy() => __pbn__NamedConsumerStrategy = null;
        private string __pbn__NamedConsumerStrategy;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeletePersistentSubscription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_group_name", IsRequired = true)]
        public string SubscriptionGroupName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdatePersistentSubscription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_group_name", IsRequired = true)]
        public string SubscriptionGroupName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"start_from", IsRequired = true)]
        public long StartFrom { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"message_timeout_milliseconds", IsRequired = true)]
        public int MessageTimeoutMilliseconds { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"record_statistics", IsRequired = true)]
        public bool RecordStatistics { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"live_buffer_size", IsRequired = true)]
        public int LiveBufferSize { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"read_batch_size", IsRequired = true)]
        public int ReadBatchSize { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"buffer_size", IsRequired = true)]
        public int BufferSize { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"max_retry_count", IsRequired = true)]
        public int MaxRetryCount { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"prefer_round_robin", IsRequired = true)]
        public bool PreferRoundRobin { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"checkpoint_after_time", IsRequired = true)]
        public int CheckpointAfterTime { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"checkpoint_max_count", IsRequired = true)]
        public int CheckpointMaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"checkpoint_min_count", IsRequired = true)]
        public int CheckpointMinCount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"subscriber_max_count", IsRequired = true)]
        public int SubscriberMaxCount { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"named_consumer_strategy")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NamedConsumerStrategy
        {
            get { return __pbn__NamedConsumerStrategy ?? ""; }
            set { __pbn__NamedConsumerStrategy = value; }
        }
        public bool ShouldSerializeNamedConsumerStrategy() => __pbn__NamedConsumerStrategy != null;
        public void ResetNamedConsumerStrategy() => __pbn__NamedConsumerStrategy = null;
        private string __pbn__NamedConsumerStrategy;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdatePersistentSubscriptionCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public UpdatePersistentSubscriptionResult Result { get; set; } = UpdatePersistentSubscriptionResult.Success;

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoContract()]
        public enum UpdatePersistentSubscriptionResult
        {
            Success = 0,
            DoesNotExist = 1,
            Fail = 2,
            AccessDenied = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreatePersistentSubscriptionCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public CreatePersistentSubscriptionResult Result { get; set; } = CreatePersistentSubscriptionResult.Success;

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoContract()]
        public enum CreatePersistentSubscriptionResult
        {
            Success = 0,
            AlreadyExists = 1,
            Fail = 2,
            AccessDenied = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeletePersistentSubscriptionCompleted : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public DeletePersistentSubscriptionResult Result { get; set; } = DeletePersistentSubscriptionResult.Success;

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoContract()]
        public enum DeletePersistentSubscriptionResult
        {
            Success = 0,
            DoesNotExist = 1,
            Fail = 2,
            AccessDenied = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectToPersistentSubscription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_id", IsRequired = true)]
        public string SubscriptionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"allowed_in_flight_messages", IsRequired = true)]
        public int AllowedInFlightMessages { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistentSubscriptionAckEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_id", IsRequired = true)]
        public string SubscriptionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"processed_event_ids")]
        public global::System.Collections.Generic.List<byte[]> ProcessedEventIds { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistentSubscriptionNakEvents : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"subscription_id", IsRequired = true)]
        public string SubscriptionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"processed_event_ids")]
        public global::System.Collections.Generic.List<byte[]> ProcessedEventIds { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get { return __pbn__Message ?? ""; }
            set { __pbn__Message = value; }
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(4, Name = @"action", IsRequired = true)]
        public NakAction Action { get; set; } = NakAction.Unknown;

        [global::ProtoBuf.ProtoContract()]
        public enum NakAction
        {
            Unknown = 0,
            Park = 1,
            Retry = 2,
            Skip = 3,
            Stop = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistentSubscriptionConfirmation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_commit_position", IsRequired = true)]
        public long LastCommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subscription_id", IsRequired = true)]
        public string SubscriptionId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"last_event_number")]
        public long LastEventNumber
        {
            get { return __pbn__LastEventNumber.GetValueOrDefault(); }
            set { __pbn__LastEventNumber = value; }
        }
        public bool ShouldSerializeLastEventNumber() => __pbn__LastEventNumber != null;
        public void ResetLastEventNumber() => __pbn__LastEventNumber = null;
        private long? __pbn__LastEventNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistentSubscriptionStreamEventAppeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event", IsRequired = true)]
        public ResolvedIndexedEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int retryCount
        {
            get { return __pbn__retryCount.GetValueOrDefault(); }
            set { __pbn__retryCount = value; }
        }
        public bool ShouldSerializeretryCount() => __pbn__retryCount != null;
        public void ResetretryCount() => __pbn__retryCount = null;
        private int? __pbn__retryCount;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscribeToStream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_stream_id", IsRequired = true)]
        public string EventStreamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"resolve_link_tos", IsRequired = true)]
        public bool ResolveLinkTos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscriptionConfirmation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_commit_position", IsRequired = true)]
        public long LastCommitPosition { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_event_number")]
        public long LastEventNumber
        {
            get { return __pbn__LastEventNumber.GetValueOrDefault(); }
            set { __pbn__LastEventNumber = value; }
        }
        public bool ShouldSerializeLastEventNumber() => __pbn__LastEventNumber != null;
        public void ResetLastEventNumber() => __pbn__LastEventNumber = null;
        private long? __pbn__LastEventNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamEventAppeared : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event", IsRequired = true)]
        public ResolvedEvent Event { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsubscribeFromStream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SubscriptionDropped : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue(SubscriptionDropReason.Unsubscribed)]
        public SubscriptionDropReason Reason
        {
            get { return __pbn__Reason ?? SubscriptionDropReason.Unsubscribed; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private SubscriptionDropReason? __pbn__Reason;

        [global::ProtoBuf.ProtoContract()]
        public enum SubscriptionDropReason
        {
            Unsubscribed = 0,
            AccessDenied = 1,
            NotFound = 2,
            PersistentSubscriptionDeleted = 3,
            SubscriberMaxCountReached = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NotHandled : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason", IsRequired = true)]
        public NotHandledReason Reason { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"additional_info")]
        public byte[] AdditionalInfo
        {
            get { return __pbn__AdditionalInfo; }
            set { __pbn__AdditionalInfo = value; }
        }
        public bool ShouldSerializeAdditionalInfo() => __pbn__AdditionalInfo != null;
        public void ResetAdditionalInfo() => __pbn__AdditionalInfo = null;
        private byte[] __pbn__AdditionalInfo;

        [global::ProtoBuf.ProtoContract()]
        public partial class MasterInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"external_tcp_address", IsRequired = true)]
            public string ExternalTcpAddress { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"external_tcp_port", IsRequired = true)]
            public int ExternalTcpPort { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"external_http_address", IsRequired = true)]
            public string ExternalHttpAddress { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"external_http_port", IsRequired = true)]
            public int ExternalHttpPort { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"external_secure_tcp_address")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ExternalSecureTcpAddress
            {
                get { return __pbn__ExternalSecureTcpAddress ?? ""; }
                set { __pbn__ExternalSecureTcpAddress = value; }
            }
            public bool ShouldSerializeExternalSecureTcpAddress() => __pbn__ExternalSecureTcpAddress != null;
            public void ResetExternalSecureTcpAddress() => __pbn__ExternalSecureTcpAddress = null;
            private string __pbn__ExternalSecureTcpAddress;

            [global::ProtoBuf.ProtoMember(6, Name = @"external_secure_tcp_port")]
            public int ExternalSecureTcpPort
            {
                get { return __pbn__ExternalSecureTcpPort.GetValueOrDefault(); }
                set { __pbn__ExternalSecureTcpPort = value; }
            }
            public bool ShouldSerializeExternalSecureTcpPort() => __pbn__ExternalSecureTcpPort != null;
            public void ResetExternalSecureTcpPort() => __pbn__ExternalSecureTcpPort = null;
            private int? __pbn__ExternalSecureTcpPort;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum NotHandledReason
        {
            NotReady = 0,
            TooBusy = 1,
            NotMaster = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScavengeDatabase : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScavengeDatabaseResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
        public ScavengeResult Result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string scavengeId
        {
            get { return __pbn__scavengeId ?? ""; }
            set { __pbn__scavengeId = value; }
        }
        public bool ShouldSerializescavengeId() => __pbn__scavengeId != null;
        public void ResetscavengeId() => __pbn__scavengeId = null;
        private string __pbn__scavengeId;

        [global::ProtoBuf.ProtoContract()]
        public enum ScavengeResult
        {
            Started = 0,
            InProgress = 1,
            Unauthorized = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IdentifyClient : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version", IsRequired = true)]
        public int Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"connection_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ConnectionName
        {
            get { return __pbn__ConnectionName ?? ""; }
            set { __pbn__ConnectionName = value; }
        }
        public bool ShouldSerializeConnectionName() => __pbn__ConnectionName != null;
        public void ResetConnectionName() => __pbn__ConnectionName = null;
        private string __pbn__ConnectionName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientIdentified : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperationResult
    {
        Success = 0,
        PrepareTimeout = 1,
        CommitTimeout = 2,
        ForwardTimeout = 3,
        WrongExpectedVersion = 4,
        StreamDeleted = 5,
        InvalidTransaction = 6,
        AccessDenied = 7,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
