// Copyright (c) Kurrent, Inc and/or licensed to Kurrent, Inc under one or more agreements.
// Kurrent, Inc licenses this file to you under the Kurrent License v1 (see LICENSE.md).

namespace KurrentDB.TestClient.Commands.DvuBasic;

internal static class StreamNamesGenerator {
	public static string GenerateName(string original, int index) {
		return string.Format("{0}-{1}", original, index);
	}

	public static string GetOriginalName(string autogenerated) {
		return autogenerated.Substring(0, autogenerated.LastIndexOf('-'));
	}
}
