// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace EventStore.SourceGenerators.Tests.Messaging.Impartial
{
	public class A
	{
		private static readonly int TypeId = Interlocked.Increment(ref NextMsgId);
		public override int MsgTypeId => TypeId;
		public static string OriginalLabelStatic { get; } = "TestMessageGroup-Impartial-A";
		public static string LabelStatic { get; set; } = "TestMessageGroup-Impartial-A";
		public override string Label => LabelStatic;
	}
}
