// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace EventStore.SourceGenerators.Tests.Messaging.ImpartialNested
{
	public class N
	{
		public partial class A
		{
			private static readonly int TypeId = Interlocked.Increment(ref NextMsgId);
			public override int MsgTypeId => TypeId;
			public static string OriginalLabelStatic { get; } = "TestMessageGroup-ImpartialNested-A";
			public static string LabelStatic { get; set; } = "TestMessageGroup-ImpartialNested-A";
			public override string Label => LabelStatic;
		}
	}
}
