// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace EventStore.SourceGenerators.Tests.Messaging
{
	public abstract partial class Message
	{
		private static int _nextMsgId = -1;
		protected static ref int NextMsgId => ref _nextMsgId;
		private static readonly int TypeId = Interlocked.Increment(ref NextMsgId);
		public virtual int MsgTypeId => TypeId;
		public virtual string Label => "";
	}
}
