// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace EventStore.SourceGenerators.Tests.Messaging.Simple
{
	public partial class A
	{
		public static string OriginalLabelStatic { get; } = "TestMessageGroup-Simple-A";
		public static string LabelStatic { get; set; } = "TestMessageGroup-Simple-A";
		public override string Label => LabelStatic;
	}

	public partial class B
	{
		public static string OriginalLabelStatic { get; } = "TestMessageGroup-Simple-B";
		public static string LabelStatic { get; set; } = "TestMessageGroup-Simple-B";
		public override string Label => LabelStatic;
	}
}
