#!/bin/sh

chown -R eventstore:eventstore /etc/eventstore
chown -R eventstore:eventstore /var/lib/eventstore
chown -R eventstore:eventstore /var/log/eventstore

ln -s /opt/eventstore/EventStore.ClusterNode /usr/bin/eventstored

ldconfig