name: Build Jammy Container

on:
  pull_request:
    paths:
      - "src/**"
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths:
      - "src/**"

jobs:
  build-container:
    uses: ./.github/workflows/build-container-reusable.yml
    with:
      container-runtime: jammy

