name: Development project automations for pull requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  call-workflow:
    uses: EventStore/Automations/.github/workflows/development-project-automation.yml@master
    with:
      resource-node-id: ${{ github.event.pull_request.node_id }}
      event-action: ${{ github.event.action }}
      event-name: ${{ github.event_name }}
    secrets:
      project-number: ${{ secrets.SERVER_DEV_PROJECT_NUMBER }}
      token: ${{ secrets.ORG_ACCESS_TOKEN }}